<?php
/**
 * Generate wp-config.php for the dev install from environment variables.
 * Used only by the "Install WordPress core on dev" GitHub Action — not shipped.
 *
 * Usage:  php tools/gen-wp-config.php <core-dir>
 * Env:    DB_NAME, DB_USER, DB_PASSWORD, DB_HOST  (DB_HOST defaults to localhost)
 */

$dir = isset( $argv[1] ) ? rtrim( $argv[1], '/' ) : 'wordpress';

/** PHP single-quoted literal from an env var. */
function env_q( $name, $required = true, $default = '' ) {
	$v = getenv( $name );
	if ( false === $v || '' === $v ) {
		if ( $required ) {
			fwrite( STDERR, "ERROR: missing required env var {$name}\n" );
			exit( 1 );
		}
		$v = $default;
	}
	return "'" . str_replace( array( '\\', "'" ), array( '\\\\', "\\'" ), $v ) . "'";
}

// Fresh salts from the WordPress.org API, with a local random fallback.
$salts = @file_get_contents( 'https://api.wordpress.org/secret-key/1.1/salt/' );
if ( ! $salts || false === strpos( $salts, 'AUTH_KEY' ) ) {
	$keys  = array( 'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT' );
	$chars = '!@#$%^&*()-_ []{}<>~`+=,.;:/?|abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
	$salts = '';
	foreach ( $keys as $k ) {
		$s = '';
		for ( $i = 0; $i < 64; $i++ ) {
			$s .= $chars[ random_int( 0, strlen( $chars ) - 1 ) ];
		}
		$s     = str_replace( array( '\\', "'" ), '', $s );
		$salts .= "define( '{$k}', '{$s}' );\n";
	}
}

$c  = "<?php\n";
$c .= "/* Generated by gen-wp-config.php for dev.omanishc.com */\n\n";
$c .= 'define( \'DB_NAME\', ' . env_q( 'DB_NAME' ) . " );\n";
$c .= 'define( \'DB_USER\', ' . env_q( 'DB_USER' ) . " );\n";
$c .= 'define( \'DB_PASSWORD\', ' . env_q( 'DB_PASSWORD' ) . " );\n";
$c .= 'define( \'DB_HOST\', ' . env_q( 'DB_HOST', false, 'localhost' ) . " );\n";
$c .= "define( 'DB_CHARSET', 'utf8mb4' );\n";
$c .= "define( 'DB_COLLATE', '' );\n\n";
$c .= rtrim( $salts ) . "\n\n";
$c .= "\$table_prefix = 'wp_';\n\n";
$c .= "define( 'WP_HOME', 'https://dev.omanishc.com' );\n";
$c .= "define( 'WP_SITEURL', 'https://dev.omanishc.com' );\n";
$c .= "define( 'WP_DEBUG', false );\n\n";
$c .= "if ( ! defined( 'ABSPATH' ) ) {\n\tdefine( 'ABSPATH', __DIR__ . '/' );\n}\n";
$c .= "require_once ABSPATH . 'wp-settings.php';\n";

$path = $dir . '/wp-config.php';
if ( false === file_put_contents( $path, $c ) ) {
	fwrite( STDERR, "ERROR: could not write {$path}\n" );
	exit( 1 );
}
echo "Wrote {$path} (" . strlen( $c ) . " bytes)\n";
